### ISSUE TITLE
AmmunitionManager

### ISSUE THREAD

**Issue by bmos** [Kelrugem/Extended-automation-and-overlays#20]
You can now remove all AmmunitionManager code from your extension (just search "if AmmunitionManager"), assuming your updated extension calls ActionAttack.onPostAttackResolve.

**Comment by bmos** [comment]
I have added a deprecation warning + proxy function into AmmmunitionManager, so until the compatibility code is removed it should work fine.

**Comment by Kelrugem** [comment]
thank you very much :) I am updating my extensions right now, so, you may hopefully not need this proxy anymore soon :)
