### ISSUE TITLE
Supernatural & Extraordinary spells roll vs. Spell Resistance

### ISSUE THREAD

**Issue by ZarestiaDev** [Kelrugem/Extended-automation-and-overlays#6]
**Issue:**
Supernatural and extraordinary abilities are by rules not subject to spell resistance. There is currently no way to get this working correctly from my testing.

**Solution proposal:**
Add a check wether there is a "supernatural" or "extraordinary" in the spell tag list. If there is one, don't roll for spell resistance. A chat output that this ability automatically overcomes spell resistance would also be neat :)

**Comment by Kelrugem** [comment]
The native ruleset allows automating this :) Each action ability has a toggle about whether or not it allows spell resistance :) Simply turn allowing SR off for such abilities :)

**Comment by Kelrugem** [comment]
![image](https://user-images.githubusercontent.com/50429899/145274810-7388eaa2-2fe2-4b02-bc60-0ec4b97595f3.png)
You can see the following in the magnifying glass of a cast action; simply toggle "SR not allowed?" :)

**Comment by Kelrugem** [comment]
If I oversee some issue here, then just reopen the issue :)
